image: docker:latest

services:
  - docker:dind

stages:
  - deploy

variables:
  CI_REGISTRY: registry.git.mpib-berlin.mpg.de
  CONTAINER_TEST_IMAGE: registry.git.mpib-berlin.mpg.de/isearch-lab/mtt:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.git.mpib-berlin.mpg.de/isearch-lab/mtt:latest
  CONTAINER_NAME: mtt-web-production
  CONTAINER_EXT_PORT: 4001
  CONTAINER_INT_PORT: 80

deploy:
  stage: deploy
  image: alpine:3.8
  environment: web-production
  only:
    - web-production
  before_script:
    - apk update
    - apk add openssh-client bash
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H -p $DEPLOYMENT_SERVER_PORT $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -p $DEPLOYMENT_SERVER_PORT gitlabci@$DEPLOYMENT_SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY; docker pull $CONTAINER_RELEASE_IMAGE; docker container stop $CONTAINER_NAME; docker container rm $CONTAINER_NAME; docker run --name $CONTAINER_NAME -d --restart always -p $CONTAINER_EXT_PORT:$CONTAINER_INT_PORT $CONTAINER_RELEASE_IMAGE"