image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release
  - deploy

variables:
  PROJECT_NAME: mtt
  CI_REGISTRY: registry.git.mpib-berlin.mpg.de
  EXP_IMG_TEST: registry.git.mpib-berlin.mpg.de/isearch-lab/mtt/mtt-exp:$CI_BUILD_REF_NAME
  EXP_IMG_RELEASE: registry.git.mpib-berlin.mpg.de/isearch-lab/mtt/mtt-exp:latest
  EXP_CONT_NAME: mtt-exp-production
  EXP_CONT_EXT_PORT: 4001
  EXP_CONT_INT_PORT: 80
  SRV_IMG_TEST: registry.git.mpib-berlin.mpg.de/isearch-lab/mtt/mtt-srv:$CI_BUILD_REF_NAME
  SRV_IMG_RELEASE: registry.git.mpib-berlin.mpg.de/isearch-lab/mtt/mtt-srv:latest

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build-exp-image:
  stage: build
  script:
    - docker build -t $EXP_IMG_TEST .
    - docker push $EXP_IMG_TEST
  only:
    - web-production
  artifacts:
    paths:
      - www/
    expire_in: 4 weeks

build-srv-image:
  stage: build
  script:
    - cd ./web-service
    - docker build -t $SRV_IMG_TEST .
    - docker push $SRV_IMG_TEST
  only:
    - web-production

release-exp-image:
  stage: release
  script:
    - docker pull $EXP_IMG_TEST
    - docker tag $EXP_IMG_TEST $EXP_IMG_RELEASE
    - docker push $EXP_IMG_RELEASE
  only:
    - web-production

release-srv-image:
  stage: release
  script:
    - docker pull $SRV_IMG_TEST
    - docker tag $SRV_IMG_TEST $SRV_IMG_RELEASE
    - docker push $SRV_IMG_RELEASE
  only:
    - web-production

deploy:
  stage: deploy
  image: alpine:latest
  environment: web-production
  only:
    - web-production
  before_script:
    - apk update
    - apk add openssh-client bash
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H -p $DEPLOYMENT_SERVER_PORT $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -p $DEPLOYMENT_SERVER_PORT gitlabci@$DEPLOYMENT_SERVER_IP "mkdir -p ~/dc-configs/${PROJECT_NAME}-prod/"
    - scp -P $DEPLOYMENT_SERVER_PORT -r ./docker-compose.yml gitlabci@$DEPLOYMENT_SERVER_IP:~/dc-configs/${PROJECT_NAME}-prod/docker-compose.yml
    - ssh -p $DEPLOYMENT_SERVER_PORT gitlabci@$DEPLOYMENT_SERVER_IP "cd ~/dc-configs/${PROJECT_NAME}-prod/; docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY; docker-compose stop; docker-compose rm --force; docker pull $EXP_IMG_RELEASE; docker pull $SRV_IMG_RELEASE; docker-compose up -d -p ${PROJECT_NAME}-prod"
