FROM node:8-alpine

# Install git
RUN apk add --no-cache \
    git \
    openssh

# Install Ionic, Cordova and HTTP server
RUN npm i -g --unsafe-perm ionic && \
    ionic --no-interactive config set -g daemon.updates false

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# Serve app
EXPOSE 80
CMD ["ionic", "serve", "-p", "80", "--no-open"]

